---
- name: update web servers
  hosts: n1

  tasks:
  - name: ensure web directory is created
    file:
      path: /home/centos/web
      state: directory

- name: update app servers
  hosts: n2

  tasks:
  - name: ensure app directory is created
    file:
      path: /home/centos/app
      state: directory
...


