---
- name: update web servers
  hosts: n1
  become: yes
  tasks:
  - name: install httpd 
    yum:
      name: httpd
      state: present

  - name: start httpd
    service:
      name: httpd
      state: started
      

  - name: enable httpd
    service:
      name: httpd
      enabled: yes
 
  - name: install git
    service:
      name: git
      state: present
      
  - name: clone git
    git:
      dest: /var/www/html 
      repo: https://github.com/ravi2krishna/ecomm.git   
   
...


