---
- name: update web servers
  hosts: n3
  become: yes
  tasks:
  - name: update  system 
    apt:
      update_cache: yes

  - name: install apache2 
    apt:
      name: apache2
      state: present

  - name: start apache2
    service:
      name: apache2
      state: started
      
  - name: enable apache2
    service:
      name: apache2
      enabled: yes
     
  - name: remove  index
    file:
      path: /var/www/html/index.html
      state: absent
      
  - name: clone git
    git:
      dest: /var/www/html 
      repo: https://github.com/ravi2krishna/ecomm.git   
   
...

