---
- name: update web servers
  hosts: all
  become: yes
  tasks:

  - name: update  system 
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install web server on centos
    package:
      name: httpd
      state: present
    when: ansible_distribution == "CentOS"
   
  - name: install web server on ubuntu
    package:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: start & enable httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: start apache2
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"
     
  - name: install git
    yum:
      name: git
      state: present
    when: ansible_distribution == "CentOS"
  
  - name: remove  index
    file:
      path: /var/www/html/index.html
      state: absent
      when: ansible_distribution == "Ubuntu"
  
  - name: clone git
    git:
      dest: /var/www/html 
      repo: https://github.com/ravi2krishna/ecomm.git   
...

