---
- name: update web servers
  hosts: all
  become: yes
  tasks:
  vars:
    user_name: ashwini 

  - name: update dynamic page 
    template:
      src: no-vars.j2
      dest: /var/www/html/dynamic.html
